# Generated by Django 5.0.1 on 2024-01-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProdavnicaNakita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.CharField(max_length=255)),
                ('grad', models.CharField(max_length=100)),
                ('postanski_broj', models.CharField(max_length=20)),
                ('placeno', models.BooleanField(default=False)),
                ('kreirano', models.DateTimeField(auto_now_add=True)),
                ('azurirano', models.DateTimeField(auto_now=True)),
                ('dodatne_informacije', models.TextField(blank=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-kreirano',),
            },
        ),
        migrations.CreateModel(
            name='StavkaPorudzbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina', models.PositiveIntegerField(default=1)),
                ('porudzbina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='Porudzbina.porudzbina')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke_porudzbina', to='ProdavnicaNakita.proizvod')),
            ],
        ),
    ]
