# Generated by Django 5.0.1 on 2024-01-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostupnost', models.BooleanField(default=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='proizvodi_slike/')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProdavnicaNakita.kategorija')),
            ],
        ),
    ]
